spring.application.name=risks-api
spring.datasource.password=risks
spring.datasource.username=risks
spring.datasource.url=jdbc:postgresql://localhost:5432/risks
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/norman
springdoc.swagger-ui.oauth.client-id=risks-api
springdoc.swagger-ui.oauth.app-name=risks-api
# Add environment variables getting info from the console
# SPRINGDOC_SWAGGER_UI_OAUTH_CLIENT_SECRET=<secret>