spring:
  application:
    name: risks-api
  datasource:
    password: risks
    username: risks
    url: jdbc:postgresql://localhost:5432/risks
  jpa:
    open-in-view: false
  threads:
    virtual:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          # Do not change name, the code refers to it!
          keycloak-admin-api:
            provider: keycloak-admin-api
            client-id: ${app.keycloak.admin-api.client-id}
            client-secret: ${app.keycloak.admin-api.client-secret}
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
        provider:
          keycloak-admin-api:
            # We define the Keycloak Admin API client in the same realm
            # as the risks-ui and risks-openapi-ui client. However, We could,
            # if we only wanted, to pick another realm for this purpose.
            # The "master" realm seems a likely choice to define the apps
            # allowed to sniff around all the Keycloak data and add users.
            issuer-uri: "${app.keycloak.url}/realms/${app.keycloak.realm}"
      # noinspection SpellCheckingInspection
      resourceserver:
        jwt:
          issuer-uri: "${app.keycloak.url}/realms/${app.keycloak.realm}"
springdoc:
  swagger-ui:
    oauth:
      client-id: ${app.open-api.client-id}
      client-secret: ${app.open-api.client-secret}
      app-name: ${app.open-api.client-id}
app:
  keycloak:
    url: http://localhost:9090
    # noinspection SpellCheckingInspection
    realm: norman
    admin-api:
      client-id: risks-api
      client-secret: admin-api-SECRET
  open-api:
    client-id: risks-openapi-ui
    client-secret: risks-openapi-ui-SECRET