spring.application.name=risks-api
spring.datasource.password=risks
spring.datasource.username=risks
spring.datasource.url=jdbc:postgresql://localhost:5432/risks
spring.jpa.open-in-view=false
spring.threads.virtual.enabled=true